name: myoro_flutter_annotations
description: A code generation library for models and theme extensions.
version: 1.1.2
repository: https://github.com/antonkoetzler/myoro_flutter_annotations
homepage: https://github.com/antonkoetzler/myoro_flutter_annotations
issue_tracker: https://github.com/antonkoetzler/myoro_flutter_annotations/issues

environment:
  sdk: ^3.8.0

topics:
  - codegen
  - annotations
  - flutter
  
dependencies:
  build_runner: ^2.4.15
  source_gen: ^2.0.0
  analyzer: ^7.4.5
  build: ^2.4.2
  dart_style: ^3.1.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_test: ^2.2.3
  source_gen_test: ^1.1.1
  mocktail: ^1.0.4
  faker: ^2.2.0
