name: myoro_flutter_annotations
description: A code generation library for models and theme extensions.
version: 1.0.0
repository: https://github.com/antonkoetzler/myoro_flutter_annotations

environment:
  sdk: ^3.7.0
  
dependencies:
  build_runner: ^2.4.15
  source_gen: ^2.0.0
  analyzer: ^7.4.5
  build: ^2.4.2
  dart_style: ^3.1.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  build_test: ^2.2.3