name: Run on Every Branch

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install actions checkout
        uses: actions/checkout@v4

      - name: Install LCOV for code coverage report generation
        run: sudo apt-get install lcov

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Dart fix check (fails if fixes exists)
        run: dart fix --dry-run .

      - name: Dart format check (fails if not formatted)
        run: dart format --line-length 120 -o none --set-exit-if-changed .

      - name: Run tests and generate coverage report
        run: bash tools/test.sh

      - name: Check coverage threshold for MFL (Must be 100%)
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE != 100" | bc -l) )); then
            echo "Code coverage is not exactly 100%."
            exit 1
          fi